<!DOCTYPE html>
<html lang="pt">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $titulo ?></title>
</head>
<body>
    <header>
        <h1>
            <?= $titulo ?>
        </h1>
    </header>

    <main>
    <?= $conteudo ?>
    </main>

    <footer>
        <p>Rodapé</p>
    </footer>
</body>
</html>